import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
await page.goto(pathToFileURL(resolve('dist/index.html')).href, { waitUntil: 'domcontentloaded' })
await page.locator('.scholar-card').first().waitFor()
const firstName = await page.locator('.scholar-card h3').first().textContent()
await page.locator('.scholar-card').first().getByRole('button', { name: /^Guardar / }).click()
assert.equal(await page.locator('.collection-toolbar button').first().locator('b').textContent(), '1')
await page.reload()
assert.equal(await page.locator('.collection-toolbar button').first().locator('b').textContent(), '1')
await page.getByRole('button', { name: /Guardadas 1/ }).click()
await page.getByRole('dialog').getByText(firstName).waitFor()
await page.keyboard.press('Escape')
await page.getByRole('dialog').waitFor({ state: 'hidden' })
await page.evaluate(() => {
  const saved = JSON.parse(localStorage.getItem('atlas-becas:favoritas:v1'))
  saved.push({ id: 'RETIRADA-TEST', nombre: 'Beca retirada de prueba', pais_destino: 'Colombia' })
  localStorage.setItem('atlas-becas:favoritas:v1', JSON.stringify(saved))
})
await page.reload()
await page.getByRole('button', { name: /Guardadas 2/ }).click()
await page.getByText('Retirada de la base').waitFor()
await page.getByRole('button', { name: 'Quitar guardada' }).last().click()
assert.equal(await page.getByRole('dialog').getByText('Beca retirada de prueba').count(), 0)
await page.keyboard.press('Escape')
await page.locator('.scholar-card .card-utility button[aria-label^="Comparar "]').nth(0).click()
await page.locator('.scholar-card .card-utility button[aria-label^="Comparar "]').nth(0).click()
await page.locator('.scholar-card .card-utility button[aria-label^="Comparar "]').nth(0).click()
assert.equal(await page.locator('.collection-toolbar button').nth(1).locator('b').textContent(), '3/3')
assert.ok(await page.locator('.scholar-card .card-utility button[aria-label^="Comparar "]:disabled').count() > 0)
await page.locator('.collection-toolbar button').nth(1).click()
assert.equal(await page.getByRole('dialog').locator('.compare-table thead th').count(), 4)
assert.ok(await page.getByRole('dialog').getByText('No verificado').count() > 0)
await page.getByRole('dialog').getByRole('button', { name: /^Quitar .* de la comparación$/ }).last().click()
assert.equal(await page.getByRole('dialog').locator('.compare-table thead th').count(), 3)
await page.keyboard.press('Escape')
const calendarButton = page.getByRole('button', { name: /^Añadir cierre de .* al calendario$/ }).first()
const [download] = await Promise.all([page.waitForEvent('download'), calendarButton.click()])
await download.saveAs(resolve('.tmp/qa-cierre.ics'))
const ics = await readFile(resolve('.tmp/qa-cierre.ics'), 'utf8')
assert.match(ics, /BEGIN:VCALENDAR\r\n/)
assert.match(ics, /DTSTART;VALUE=DATE:\d{8}/)
assert.match(ics, /DTEND;VALUE=DATE:\d{8}/)
assert.match(ics, /URL:https:\/\//)
assert.match(ics, /Comprueba el plazo/)
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } })
mobile.on('pageerror', (error) => errors.push(`mobile: ${error.message}`))
await mobile.goto(pathToFileURL(resolve('dist/index.html')).href, { waitUntil: 'domcontentloaded' })
for (let index = 0; index < 3; index += 1) await mobile.locator('.card-utility button[aria-label^="Comparar "]').first().click()
await mobile.locator('.collection-toolbar button').nth(1).click()
await mobile.getByRole('dialog').waitFor()
assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
assert.equal(await mobile.locator('.compare-scroll').evaluate((element) => element.scrollWidth > element.clientWidth), true)
await mobile.close()
assert.deepEqual(errors, [])
console.log(JSON.stringify({ favoritePersists: true, retiredVisible: true, compareMax: 3, downloaded: download.suggestedFilename(), pageErrors: errors }))
await browser.close()
