import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const errors = []
const target = pathToFileURL(resolve('dist/index.html')).href
await mkdir('.tmp', { recursive: true })

const desktop = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
desktop.on('pageerror', error => errors.push(`desktop: ${error.message}`))
await desktop.goto(target, { waitUntil: 'domcontentloaded' })
await desktop.locator('.results-indicator strong').waitFor()
await desktop.waitForTimeout(2200)
const initial = await desktop.locator('.results-indicator strong').textContent()
const mapVisible = await desktop.locator('.leaflet-container').isVisible()
const countryShapes = await desktop.locator('.leaflet-overlay-pane canvas').count()
await desktop.screenshot({ path: '.tmp/desktop.png', fullPage: true })
await desktop.locator('select').first().selectOption('Alemania')
const germany = await desktop.locator('.results-indicator strong').textContent()
await desktop.locator('select').nth(4).selectOption('abierta')
const germanyOpen = await desktop.locator('.results-indicator strong').textContent()
await desktop.locator('button[aria-label^="Ubicar"]').first().click()
await desktop.locator('.leaflet-popup-content a[href^="https://"]').waitFor({ timeout: 5000 })
const popupOfficial = await desktop.locator('.leaflet-popup-content a[href^="https://"]').count()
const popupColor = await desktop.locator('.leaflet-popup-content a[href^="https://"]').evaluate((link) => getComputedStyle(link).color)
await desktop.locator('a[href="#/fuentes"]').click()
await desktop.locator('.source-list a').first().waitFor()
const sources = await desktop.locator('.source-list a').count()
await desktop.locator('a[href="#/metodo"]').click()
await desktop.locator('.method-limits a').first().waitFor()
const exclusions = await desktop.locator('.method-limits a').count()

const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
mobile.on('pageerror', error => errors.push(`mobile: ${error.message}`))
await mobile.goto(target, { waitUntil: 'domcontentloaded' })
await mobile.locator('.leaflet-container').waitFor()
await mobile.waitForTimeout(1800)
await mobile.screenshot({ path: '.tmp/mobile.png', fullPage: true })
const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
const offlineContext = await browser.newContext()
await offlineContext.route(/^https?:\/\//, route => route.abort())
const offlinePage = await offlineContext.newPage()
offlinePage.on('pageerror', error => errors.push('offline: ' + error.message))
await offlinePage.goto(target, { waitUntil: 'domcontentloaded' })
await offlinePage.locator('.leaflet-overlay-pane canvas').first().waitFor()
const offlineMap = await offlinePage.locator('.leaflet-overlay-pane canvas').count()
assert.equal(initial, '44')
assert.equal(mapVisible, true)
assert.ok(countryShapes > 0)
assert.equal(germany, '6')
assert.equal(germanyOpen, '1')
assert.equal(popupOfficial, 1)
assert.equal(popupColor, 'rgb(255, 255, 255)')
assert.equal(await desktop.locator('a[download]').count(), 0)
assert.equal(await desktop.locator('.method-download').count(), 0)
assert.equal(sources, 44)
assert.equal(exclusions, 4)
assert.equal(overflow, false)
assert.ok(offlineMap > 0)
assert.deepEqual(errors, [])
console.log(JSON.stringify({ initial, mapVisible, countryShapes, germany, germanyOpen, popupOfficial, popupColor, sources, exclusions, mobileHorizontalOverflow: overflow, offlineMap, errors }, null, 2))
await offlineContext.close()
await browser.close()
