import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const errors = []
const target = pathToFileURL(resolve('dist/index.html')).href
await mkdir('.tmp', { recursive: true })

const desktop = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
desktop.on('pageerror', error => errors.push(`desktop: ${error.message}`))
await desktop.goto(target, { waitUntil: 'domcontentloaded' })
await desktop.locator('.results-indicator strong').waitFor()
await desktop.waitForTimeout(2200)
const initial = await desktop.locator('.results-indicator strong').textContent()
assert.equal(await desktop.locator('.card-warning', { hasText: 'Revisión pendiente' }).count(), 2)
assert.equal(await desktop.locator('.card-verified').count(), 44)
const mapVisible = await desktop.locator('.leaflet-container').isVisible()
const countryShapes = await desktop.locator('.leaflet-overlay-pane canvas').count()
await desktop.screenshot({ path: '.tmp/desktop.png', fullPage: true })
const firstDetails = desktop.locator('.card-detail-link').first()
await firstDetails.focus()
await desktop.keyboard.press('Enter')
const detail = desktop.getByRole('dialog', { name: /.+/ })
await detail.waitFor()
assert.equal(await detail.getByText('Requisitos clave').count(), 1)
assert.equal(await detail.getByText('Idioma requerido').count(), 1)
assert.equal(await detail.getByText('Monto y moneda').count(), 1)
assert.equal(await detail.getByText('Precisión del marcador').count(), 1)
assert.equal(await detail.locator('a[href^="https://"]').count(), 1)
assert.equal(await desktop.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Cerrar ficha')
await desktop.keyboard.press('Shift+Tab')
assert.equal(await desktop.evaluate(() => document.activeElement?.textContent?.includes('Ver convocatoria oficial')), true)
await desktop.keyboard.press('Escape')
await detail.waitFor({ state: 'hidden' })
await desktop.waitForTimeout(100)
assert.equal(await firstDetails.evaluate((button) => document.activeElement === button), true)
await desktop.getByRole('button', { name: 'Abiertas ahora' }).click()
const quickOpen = Number(await desktop.locator('.results-indicator strong').textContent())
assert.ok(quickOpen > 0 && quickOpen < 44)
assert.equal(await desktop.locator('.scholar-card').count(), quickOpen)
assert.equal(await desktop.locator('.scholar-card .status:not(.status-abierta)').count(), 0)
await desktop.getByRole('button', { name: 'Cierran pronto' }).click()
const quickSoon = Number(await desktop.locator('.results-indicator strong').textContent())
assert.ok(quickSoon > 0 && quickSoon <= quickOpen)
await desktop.getByRole('button', { name: 'Recurrentes' }).click()
assert.equal(await desktop.locator('.scholar-card .status:not(.status-recurrente)').count(), 0)
await desktop.getByRole('button', { name: 'Todas', exact: true }).click()
await desktop.getByLabel('Ordenar resultados').selectOption('cierre')
const firstClosing = await desktop.locator('.scholar-card .closing').first().textContent()
assert.ok(!firstClosing.includes('Por confirmar'))
await desktop.getByLabel('Ordenar resultados').selectOption('nombre')
await desktop.locator('select').first().selectOption('Alemania')
const germany = await desktop.locator('.results-indicator strong').textContent()
await desktop.locator('select').nth(4).selectOption('abierta')
const germanyOpen = await desktop.locator('.results-indicator strong').textContent()
await desktop.locator('button[aria-label^="Ubicar"]').first().click()
await desktop.locator('.leaflet-popup-content a[href^="https://"]').waitFor({ timeout: 5000 })
const popupOfficial = await desktop.locator('.leaflet-popup-content a[href^="https://"]').count()
const popupColor = await desktop.locator('.leaflet-popup-content a[href^="https://"]').evaluate((link) => getComputedStyle(link).color)
await desktop.locator('.popup-details').click()
await desktop.getByRole('dialog').waitFor()
await desktop.getByRole('button', { name: 'Volver a resultados' }).click()
await desktop.getByRole('dialog').waitFor({ state: 'hidden' })
await desktop.locator('a[href="#/fuentes"]').click()
await desktop.locator('.source-list a').first().waitFor()
const sources = await desktop.locator('.source-list a').count()
await desktop.locator('a[href="#/metodo"]').click()
await desktop.locator('.method-limits a').first().waitFor()
const exclusions = await desktop.locator('.method-limits a').count()

const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
mobile.on('pageerror', error => errors.push(`mobile: ${error.message}`))
await mobile.goto(target, { waitUntil: 'domcontentloaded' })
await mobile.locator('.results-list').waitFor()
assert.equal(await mobile.locator('.results-list').isVisible(), true)
assert.equal(await mobile.locator('.map-panel').isVisible(), false)
await mobile.getByRole('button', { name: 'EXPLORAR EL MAPA' }).click()
await mobile.locator('.leaflet-container').waitFor()
assert.equal(await mobile.locator('.map-panel').isVisible(), true)
await mobile.getByRole('button', { name: 'Lista', exact: true }).click()
await mobile.locator('select').first().selectOption('Alemania')
assert.equal(await mobile.locator('.results-indicator strong').textContent(), '6')
await mobile.getByRole('button', { name: 'Mapa', exact: true }).click()
await mobile.locator('.leaflet-container').waitFor()
assert.equal(await mobile.locator('.results-list').isVisible(), false)
assert.equal(await mobile.locator('.leaflet-overlay-pane canvas').first().isVisible(), true)
await mobile.getByRole('button', { name: 'Lista', exact: true }).click()
assert.equal(await mobile.locator('.results-list').isVisible(), true)
assert.equal(await mobile.locator('.results-indicator strong').textContent(), '6')
await mobile.locator('.card-detail-link').first().click()
await mobile.getByRole('dialog').waitFor()
await mobile.keyboard.press('Escape')
await mobile.getByRole('dialog').waitFor({ state: 'hidden' })
await mobile.locator('select').first().selectOption('todos')
await mobile.locator('.card-actions button[aria-label^="Ubicar"]').first().click()
await mobile.locator('.leaflet-popup-content .popup-details').waitFor()
await mobile.getByRole('button', { name: 'Lista', exact: true }).click()
assert.equal(await mobile.locator('.scholar-card.is-selected').count(), 1)
await mobile.waitForTimeout(1800)
await mobile.screenshot({ path: '.tmp/mobile.png', fullPage: true })
await mobile.getByRole('button', { name: 'Recurrentes' }).click()
assert.equal(await mobile.locator('.scholar-card .status:not(.status-recurrente)').count(), 0)
await mobile.getByLabel('Ordenar resultados').selectOption('pais')
await mobile.locator('select').first().selectOption('Japón')
await mobile.getByRole('button', { name: 'Abiertas ahora' }).click()
await mobile.getByText('Sin aperturas confirmadas').waitFor()
await mobile.getByRole('button', { name: 'Mapa', exact: true }).click()
await mobile.locator('.map-empty').waitFor()
await mobile.locator('.destination-list button').first().click()
assert.equal(await mobile.locator('.map-panel').isVisible(), true)
const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
const offlineContext = await browser.newContext()
await offlineContext.route(/^https?:\/\//, route => route.abort())
const offlinePage = await offlineContext.newPage()
offlinePage.on('pageerror', error => errors.push('offline: ' + error.message))
await offlinePage.goto(target, { waitUntil: 'domcontentloaded' })
await offlinePage.locator('.leaflet-overlay-pane canvas').first().waitFor()
const offlineMap = await offlinePage.locator('.leaflet-overlay-pane canvas').count()
assert.equal(initial, '44')
assert.equal(mapVisible, true)
assert.ok(countryShapes > 0)
assert.equal(germany, '6')
assert.equal(germanyOpen, '1')
assert.equal(popupOfficial, 1)
assert.equal(popupColor, 'rgb(255, 255, 255)')
assert.equal(await desktop.locator('a[download]').count(), 0)
assert.equal(await desktop.locator('.method-download').count(), 0)
assert.equal(sources, 44)
assert.equal(exclusions, 4)
assert.equal(overflow, false)
assert.ok(offlineMap > 0)
const reduced = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })
reduced.on('pageerror', error => errors.push(`reduced: ${error.message}`))
await reduced.goto(target, { waitUntil: 'domcontentloaded' })
await reduced.getByRole('button', { name: 'Mapa', exact: true }).click()
await reduced.locator('.leaflet-container').waitFor()
assert.equal(await reduced.locator('.map-panel').isVisible(), true)
await reduced.close()
assert.deepEqual(errors, [])
console.log(JSON.stringify({ initial, mapVisible, countryShapes, germany, germanyOpen, popupOfficial, popupColor, sources, exclusions, mobileHorizontalOverflow: overflow, offlineMap, errors }, null, 2))
await offlineContext.close()
await browser.close()
